[build]
  command = "yarn build"
  functions = "build"
  publish = "build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-discord"

